static security_questions:Vec<String> = Vec::from([
    String::from("What is your mother's maiden name?"),
    String::from("What is your mother's middle name?"),
    String::from("What is your father's middle name?"),
    String::from("Where did your parents meet?"),
    String::from("What was the name of your first crush?"),
    String::from("What is the name of your first pet?"),
    String::from("What was the name of your first stuffed animal?"),
    String::from("What is your favorite food?"),
    String::from("Which is your favorite Pokemon?"),
    String::from("Who is your favorite YouTuber/streamer?"),
    String::from("What is your favorite song?"),
    String::from("What was the first concert you ever attended?"),
    String::from("What was the name of your favorite teacher?"),
    String::from("What was the last name of your third grade teacher?"),
    String::from("What was the name of your elementary school?"),
    String::from("What brand of backpack do you have?"),
    String::from("What brand of sunglasses do you have?"),
    String::from("What kind of printer do you have?"),
    String::from("What model of laptop do you have?"),
    String::from("What is your favorite video game?"),
    String::from("What is your favorite headset/what headset do you use the most?"),
    String::from("What is your favorite programming language?"),
    String::from("What was the first programming language you learned?"),
    String::from("What is your favorite programming IDE/editor?"),
    String::from("What is the name of the last company you called for support?"),
]);